import type {
  Residence,
  ResidenceDetailContent,
  ResidenceGridContent,
  ResidencePhoto,
  ResidenceStatus,
} from "@cinematic/section-library";

/**
 * The eighteen Aurelia residences. Facts are authored once here; the listing
 * (`/residences`) and the detail pages (`/residences/[slug]`) both read them.
 *
 * Photography is licensed Unsplash placeholder material. The key plans and
 * floor plans are drawings generated by `scripts/build-residence-plans.mjs`
 * from this same inventory, so they are never cropped to fill a frame.
 */

function shot(id: string, room: string, alt: string, caption: string): ResidencePhoto {
  return {
    id,
    src: `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1800&q=80`,
    alt,
    caption,
    room,
  };
}

/** The photographic library the units draw from, so no unit repeats a frame twice. */
const PHOTOS = {
  gardenFacade: shot(
    "photo-1600585154340-be6161a56a0c",
    "From the garden",
    "Dark timber and limewashed stone seen across a lawn in afternoon light.",
    "The garden front. Timber above, stone at the base.",
  ),
  gardenWall: shot(
    "photo-1600566753190-17f0baa2a6c3",
    "The garden wall",
    "A dark timber wall with a single gate opening into a planted court.",
    "The gate from the path into the private court.",
  ),
  gardenLiving: shot(
    "photo-1513694203232-719a280e022f",
    "Living room",
    "A pale living room with a low table and dried grasses in a tall vase.",
    "The living room, kept pale so the water does the colouring.",
  ),
  gardenKitchen: shot(
    "photo-1600585152220-90363fe7e115",
    "Kitchen",
    "A kitchen with timber fronts, black pendants, and a pale stone island.",
    "Timber fronts and a stone island, with stools along one side.",
  ),
  gardenPlants: shot(
    "photo-1583847268964-b28dc8f51f92",
    "Toward the garden",
    "A living room with plants and a rug, looking toward a garden door.",
    "The garden door sits at the end of the living room.",
  ),
  gardenLawn: shot(
    "photo-1600607688969-a5bfcd646154",
    "From the lawn",
    "A timber and glass house seen from a lawn under a mature tree.",
    "The building from the shared lawn, late in the day.",
  ),
  gardenBath: shot(
    "photo-1631889993959-41b4e9c6e3c5",
    "Bathroom",
    "A bathroom in timber and pale tile with a long mirror over the basin.",
    "Timber, pale tile, and a window at the end of the bath.",
  ),
  gardenStair: shot(
    "photo-1502005229762-cf1b2da7c5d6",
    "To the lower level",
    "A pale stair with a timber handrail turning down out of a hall.",
    "The stair down to the workshop and the store.",
  ),
  gardenEntry: shot(
    "photo-1600585154526-990dced4db0d",
    "The entrance",
    "A lit timber doorway opening into a pale hall after dark.",
    "The entrance from the path, seen after dark.",
  ),
  gardenCounter: shot(
    "photo-1484154218962-a197022b5858",
    "Kitchen",
    "A white kitchen with a long counter, open shelves, and a tall window.",
    "A long counter, with the window over the sink.",
  ),
  harborTerrace: shot(
    "photo-1600573472591-ee6b68d14c68",
    "Terrace",
    "A sliding door open onto a terrace with a single chair and water beyond.",
    "The terrace door stays open most of the summer.",
  ),
  harborTimber: shot(
    "photo-1600607687939-ce8a6c25118c",
    "Living room",
    "A tall living room with a timber wall and a window the height of the room.",
    "One timber wall, and a window the height of the room.",
  ),
  harborRound: shot(
    "photo-1616486338812-3dadae4b4ace",
    "Dining end",
    "A pale living room with a round table, a low sofa, and a woven rug.",
    "A round table at the window end of the room.",
  ),
  harborJetty: shot(
    "photo-1439066615861-d1af74d74000",
    "The jetty",
    "A wooden jetty reaching into still water under a clear sky.",
    "The jetty below the building, early in the morning.",
  ),
  harborLight: shot(
    "photo-1507089947368-19c1da9775ae",
    "Window wall",
    "A living room with pale walls, long windows, and a cased ceiling.",
    "Long windows on the water side of the room.",
  ),
  harborCorner: shot(
    "photo-1519710164239-da123dc03ef4",
    "Reading corner",
    "A white corner with an arc lamp, a small table, and two chairs.",
    "A corner kept for reading, by the window.",
  ),
  harborBath: shot(
    "photo-1600566752355-35792bedcfea",
    "Bathroom",
    "A bathroom in dark stone with a free-standing bath under a high window.",
    "Dark stone, and a bath under the high window.",
  ),
  harborHearth: shot(
    "photo-1616137466211-f939a420be84",
    "By the hearth",
    "A living room with a low fireplace, pale walls, and two sofas.",
    "A low hearth on the inland wall.",
  ),
  harborBedroom: shot(
    "photo-1598928506311-c55ded91a20c",
    "Bedroom",
    "A bedroom kept dark, with curtains half drawn across a wide window.",
    "The main bedroom, kept dark, facing the channel.",
  ),
  harborBoat: shot(
    "photo-1476514525535-07fb3b4ae5f1",
    "The water",
    "A wooden boat on still water with low hills behind it.",
    "The channel off the quay, on a still morning.",
  ),
  harborOpen: shot(
    "photo-1503174971373-b1f69850bded",
    "Living room",
    "A living room opening onto a terrace through a wall of glass.",
    "The living room opens the full width of the terrace.",
  ),
  harborGrey: shot(
    "photo-1600121848594-d8644e57abab",
    "Along the window",
    "A grey living room with a long window and a low shelf along one wall.",
    "A long window, and a shelf the length of the wall.",
  ),
  penthouseDining: shot(
    "photo-1600607687920-4e2a09cf159d",
    "Dining",
    "A long black dining table under a roof light, with a stair behind it.",
    "The dining table sits under the roof light.",
  ),
  penthouseLong: shot(
    "photo-1604014237800-1c9102c219da",
    "Living room",
    "A long room with a timber wall, a dining end, and a view west.",
    "The room runs the depth of the building, west to east.",
  ),
  penthouseCeiling: shot(
    "photo-1618221195710-dd6b41faaea6",
    "Living room",
    "A living room under a timber ceiling with a low seating group.",
    "The ceiling follows the pitch of the roof.",
  ),
  penthousePendants: shot(
    "photo-1615529182904-14819c35db37",
    "Seating group",
    "Woven pendant lights hung low over a pale seating group.",
    "Pendants hung low over the seating group.",
  ),
  penthouseStair: shot(
    "photo-1600566753086-00f18fb6b3ea",
    "To the roof",
    "A timber and steel stair rising from a pale living room to a roof hatch.",
    "The stair from the living room to the solarium.",
  ),
  penthouseBedroom: shot(
    "photo-1617104678098-de229db51175",
    "Bedroom",
    "A bedroom in dark tones looking out into trees through a wide window.",
    "The second bedroom looks inland, into the trees.",
  ),
  penthouseBench: shot(
    "photo-1616594039964-ae9021a400a0",
    "Bedroom",
    "A bedroom with heavy curtains and a bench at the foot of the bed.",
    "Heavy curtains, and a bench at the foot of the bed.",
  ),
  penthouseDusk: shot(
    "photo-1600585153490-76fb20a32601",
    "At dusk",
    "The top of a dark timber building lit from within at dusk.",
    "The top of the building, lit from inside at dusk.",
  ),
  penthouseFrames: shot(
    "photo-1600210492486-724fe5c67fb0",
    "Sitting room",
    "A living room with a leather sofa and a wall hung with framed prints.",
    "A leather sofa, and a wall kept for framed prints.",
  ),
  penthousePlants: shot(
    "photo-1567767292278-a4f21aa2d36e",
    "Corner window",
    "A pale living room with tall plants and a glass table.",
    "Tall plants at the corner window.",
  ),
} satisfies Record<string, ResidencePhoto>;

type PhotoKey = keyof typeof PHOTOS;

const FLOOR_LABELS = ["Garden level", "First floor", "Second floor", "Roof level"] as const;

interface TypeDefaults {
  label: string;
  bathrooms: number;
  outdoorLabel: string;
  features: string[];
}

const TYPES: Record<string, TypeDefaults> = {
  garden: {
    label: "Garden residence",
    bathrooms: 2,
    outdoorLabel: "Garden",
    features: [
      "Private lower level",
      "Direct garden access",
      "Underfloor heating",
      "Stone floors",
      "Timber joinery",
      "Two parking bays",
      "Cycle store",
      "Heat pump",
    ],
  },
  harbor: {
    label: "Harbor residence",
    bathrooms: 2,
    outdoorLabel: "Terrace",
    features: [
      "Terrace over the water",
      "Underfloor heating",
      "Stone floors",
      "Timber joinery",
      "One parking bay",
      "Cycle store",
      "Heat pump",
      "Storage room",
    ],
  },
  penthouse: {
    label: "Penthouse residence",
    bathrooms: 3,
    outdoorLabel: "Solarium",
    features: [
      "Roof solarium",
      "Own stair to the roof",
      "Ceilings to the roof pitch",
      "Underfloor heating",
      "Stone floors",
      "Timber joinery",
      "Two parking bays",
      "Heat pump",
    ],
  },
};

interface UnitSpec {
  number: string;
  type: keyof typeof TYPES;
  block: string;
  floor: number;
  bedrooms: number;
  interiorSqm: number;
  outdoorSqm: number;
  status: ResidenceStatus;
  completion: string;
  orientation: string;
  description: string;
  photos: PhotoKey[];
}

const QUAY_ORIENTATION = "South-west, over the water";
const PATH_ORIENTATION = "West, over the garden to the channel";

const UNITS: UnitSpec[] = [
  {
    number: "011",
    type: "garden",
    block: "Quay",
    floor: 0,
    bedrooms: 3,
    interiorSqm: 132,
    outdoorSqm: 46,
    status: "available",
    completion: "Q2 2027",
    orientation: QUAY_ORIENTATION,
    description:
      "Three bedrooms on one level, with a second door straight onto the garden. The lower level holds a workshop, a store, and the plant room. The living room reads the water across the lawn.",
    photos: ["gardenFacade", "gardenLiving", "gardenKitchen", "gardenStair"],
  },
  {
    number: "012",
    type: "garden",
    block: "Quay",
    floor: 0,
    bedrooms: 3,
    interiorSqm: 128,
    outdoorSqm: 38,
    status: "reserved",
    completion: "Q2 2027",
    orientation: QUAY_ORIENTATION,
    description:
      "The narrower of the Quay garden homes. The kitchen sits at the path end and the three bedrooms run along the garden wall, so the noise of the road never reaches them.",
    photos: ["gardenCounter", "gardenPlants", "gardenBath"],
  },
  {
    number: "013",
    type: "garden",
    block: "Quay",
    floor: 0,
    bedrooms: 3,
    interiorSqm: 136,
    outdoorSqm: 52,
    status: "available",
    completion: "Q2 2027",
    orientation: QUAY_ORIENTATION,
    description:
      "The end home in the Quay block, with windows on two sides. The garden wraps the corner and takes the evening light until late.",
    photos: ["gardenLawn", "gardenLiving", "gardenKitchen", "gardenEntry"],
  },
  {
    number: "021",
    type: "garden",
    block: "Path",
    floor: 0,
    bedrooms: 3,
    interiorSqm: 141,
    outdoorSqm: 58,
    status: "sold",
    completion: "Q2 2027",
    orientation: PATH_ORIENTATION,
    description:
      "A wide plan with the living room across the garden front. The lower level is laid out for a studio rather than storage, with a window onto the light well.",
    photos: ["gardenWall", "gardenPlants", "gardenStair"],
  },
  {
    number: "022",
    type: "garden",
    block: "Path",
    floor: 0,
    bedrooms: 3,
    interiorSqm: 134,
    outdoorSqm: 44,
    status: "available",
    completion: "Q2 2027",
    orientation: PATH_ORIENTATION,
    description:
      "Three bedrooms, two baths, and a utility room off the hall. The garden is enclosed on three sides by the timber wall.",
    photos: ["gardenKitchen", "gardenLiving", "gardenBath", "gardenWall"],
  },
  {
    number: "023",
    type: "garden",
    block: "Path",
    floor: 0,
    bedrooms: 3,
    interiorSqm: 148,
    outdoorSqm: 62,
    status: "available",
    completion: "Q2 2027",
    orientation: PATH_ORIENTATION,
    description:
      "The largest garden home. The living room, the kitchen, and the main bedroom all open onto the same stretch of garden, under the row of birches along the path.",
    photos: ["gardenFacade", "gardenCounter", "gardenPlants", "gardenLawn"],
  },
  {
    number: "111",
    type: "harbor",
    block: "Quay",
    floor: 1,
    bedrooms: 2,
    interiorSqm: 99,
    outdoorSqm: 18,
    status: "available",
    completion: "Q2 2027",
    orientation: QUAY_ORIENTATION,
    description:
      "Two bedrooms and one long room facing the channel. The terrace runs the width of the living room and sits above the jetty.",
    photos: ["harborTerrace", "harborTimber", "harborBedroom"],
  },
  {
    number: "112",
    type: "harbor",
    block: "Quay",
    floor: 1,
    bedrooms: 2,
    interiorSqm: 97,
    outdoorSqm: 14,
    status: "sold",
    completion: "Q2 2027",
    orientation: QUAY_ORIENTATION,
    description:
      "The compact Quay plan. The kitchen is open to the living room and the second bedroom takes the inland window, which keeps it cool in summer.",
    photos: ["harborRound", "harborCorner", "harborBath"],
  },
  {
    number: "113",
    type: "harbor",
    block: "Quay",
    floor: 1,
    bedrooms: 2,
    interiorSqm: 104,
    outdoorSqm: 22,
    status: "available",
    completion: "Q2 2027",
    orientation: QUAY_ORIENTATION,
    description:
      "A corner home with the terrace on the water side and a second window facing north up the coast. The main bedroom has its own shower room.",
    photos: ["harborOpen", "harborLight", "harborJetty", "harborBedroom"],
  },
  {
    number: "121",
    type: "harbor",
    block: "Path",
    floor: 1,
    bedrooms: 2,
    interiorSqm: 101,
    outdoorSqm: 19,
    status: "available",
    completion: "Q2 2027",
    orientation: PATH_ORIENTATION,
    description:
      "The living room sits over the garden, with the channel beyond the trees. A low hearth stands on the inland wall.",
    photos: ["harborHearth", "harborGrey", "harborBath"],
  },
  {
    number: "122",
    type: "harbor",
    block: "Path",
    floor: 1,
    bedrooms: 2,
    interiorSqm: 98,
    outdoorSqm: 16,
    status: "reserved",
    completion: "Q2 2027",
    orientation: PATH_ORIENTATION,
    description:
      "Two bedrooms off a short hall, with the living room and kitchen in one room along the garden front. A storage room sits at the stair.",
    photos: ["harborGrey", "harborCorner", "harborBoat"],
  },
  {
    number: "211",
    type: "harbor",
    block: "Quay",
    floor: 2,
    bedrooms: 2,
    interiorSqm: 103,
    outdoorSqm: 21,
    status: "available",
    completion: "Q4 2027",
    orientation: QUAY_ORIENTATION,
    description:
      "One floor higher, so the terrace clears the jetty roof and reads straight out to the channel mouth. The ceiling is a little taller than the floor below.",
    photos: ["harborLight", "harborTerrace", "harborJetty", "harborBedroom"],
  },
  {
    number: "212",
    type: "harbor",
    block: "Quay",
    floor: 2,
    bedrooms: 2,
    interiorSqm: 100,
    outdoorSqm: 17,
    status: "available",
    completion: "Q4 2027",
    orientation: QUAY_ORIENTATION,
    description:
      "The plan repeats 112 a floor up, with the kitchen moved to the inland wall. That leaves the whole water side of the room to the windows.",
    photos: ["harborTimber", "harborRound", "harborBoat"],
  },
  {
    number: "221",
    type: "harbor",
    block: "Path",
    floor: 2,
    bedrooms: 2,
    interiorSqm: 97,
    outdoorSqm: 15,
    status: "sold",
    completion: "Q4 2027",
    orientation: PATH_ORIENTATION,
    description:
      "The last of the Path harbor homes. Two bedrooms, one bath and one shower room, and a terrace at the south end of the living room.",
    photos: ["harborOpen", "harborHearth", "harborCorner"],
  },
  {
    number: "311",
    type: "penthouse",
    block: "Quay",
    floor: 3,
    bedrooms: 3,
    interiorSqm: 164,
    outdoorSqm: 48,
    status: "available",
    completion: "Q4 2027",
    orientation: QUAY_ORIENTATION,
    description:
      "The top of the Quay block, under the pitch of the roof. A stair off the hall goes up to a solarium with the channel on one side and the hills on the other.",
    photos: ["penthouseCeiling", "penthouseStair", "penthouseBedroom"],
  },
  {
    number: "312",
    type: "penthouse",
    block: "Quay",
    floor: 3,
    bedrooms: 4,
    interiorSqm: 186,
    outdoorSqm: 72,
    status: "reserved",
    completion: "Q4 2027",
    orientation: QUAY_ORIENTATION,
    description:
      "Four bedrooms and a room long enough to dine at one end and sit at the other. A roof light runs over the dining table. The solarium takes the whole west corner.",
    photos: ["penthouseDining", "penthouseLong", "penthouseBench", "penthouseDusk"],
  },
  {
    number: "321",
    type: "penthouse",
    block: "Path",
    floor: 3,
    bedrooms: 3,
    interiorSqm: 171,
    outdoorSqm: 54,
    status: "available",
    completion: "Q4 2027",
    orientation: PATH_ORIENTATION,
    description:
      "Three bedrooms along the inland wall and one long room facing the garden. The stair to the roof rises out of the living room rather than the hall.",
    photos: ["penthousePendants", "penthousePlants", "penthouseStair"],
  },
  {
    number: "322",
    type: "penthouse",
    block: "Path",
    floor: 3,
    bedrooms: 4,
    interiorSqm: 198,
    outdoorSqm: 86,
    status: "available",
    completion: "Q4 2027",
    orientation: PATH_ORIENTATION,
    description:
      "The largest home at Aurelia, on the corner of the Path block. Four bedrooms, three baths, and a solarium that keeps the sun from the middle of the morning until it goes down over the water.",
    photos: ["penthouseLong", "penthouseFrames", "penthouseBench", "penthouseDusk"],
  },
];

function build(spec: UnitSpec): Residence {
  const type = TYPES[spec.type];
  if (!type) {
    throw new Error(`Unknown residence type: ${spec.type}`);
  }

  return {
    slug: spec.number,
    number: spec.number,
    name: `No. ${spec.number}`,
    type: spec.type,
    typeLabel: type.label,
    block: spec.block,
    floor: spec.floor,
    floorLabel: FLOOR_LABELS[spec.floor] ?? `Floor ${spec.floor}`,
    bedrooms: spec.bedrooms,
    bathrooms: type.bathrooms,
    interiorSqm: spec.interiorSqm,
    outdoorSqm: spec.outdoorSqm,
    outdoorLabel: type.outdoorLabel,
    orientation: spec.orientation,
    status: spec.status,
    completion: spec.completion,
    description: spec.description,
    features: type.features,
    schematic: {
      src: `/residences/key-${spec.number}.svg`,
      alt: `Key plan: ${type.label} No. ${spec.number} marked on the ${
        FLOOR_LABELS[spec.floor] ?? `floor ${spec.floor}`
      } of the ${spec.block} block.`,
      caption: `Key plan — where No. ${spec.number} sits on its floor.`,
    },
    plan: {
      src: `/residences/plan-${spec.number}.svg`,
      alt: `Floor plan: No. ${spec.number}, ${spec.bedrooms} bedrooms, ${spec.interiorSqm} m² inside and ${spec.outdoorSqm} m² of ${type.outdoorLabel.toLowerCase()}.`,
      caption: `Floor plan — No. ${spec.number}, ${spec.interiorSqm} m².`,
    },
    photos: spec.photos.map((key) => PHOTOS[key]),
  };
}

export const residences: Residence[] = UNITS.map(build);

export const residenceGrid: Omit<ResidenceGridContent, "residences"> = {
  crumbs: [{ label: "Home", href: "/" }, { label: "Select a residence" }],
  eyebrow: "Residences",
  headingLines: ["Eighteen homes", "above the harbour"],
  intro:
    "Six garden homes, eight over the quay, and four under the roof. Filter by type or by bedrooms, then open a unit to see its plan.",
  controlsLabel: "Filter and sort the residences",
  typeLabel: "Type",
  bedroomsLabel: "Bedrooms",
  sortLabel: "Sort by",
  allLabel: "All",
  resetLabel: "Reset",
  countOne: "residence",
  countMany: "residences",
  countNone: "No residences",
  emptyHeading: "Nothing matches those two filters.",
  emptyBody:
    "There is no home at Aurelia with that combination of type and bedroom count. Clear the filters to see all eighteen.",
  bedroomsSuffixOne: "bed",
  bedroomsSuffixMany: "bed",
  types: [
    { id: "garden", label: "Garden residence" },
    { id: "harbor", label: "Harbor residence" },
    { id: "penthouse", label: "Penthouse residence" },
  ],
  sortOptions: [
    { id: "relevant", label: "Block and floor" },
    { id: "area-asc", label: "Smallest area" },
    { id: "area-desc", label: "Largest area" },
  ],
  cardCtaLabel: "View residence",
  listLabel: "Residences",
};

export const residenceDetailLabels: Omit<
  ResidenceDetailContent,
  "crumbs" | "residence" | "similar"
> = {
  bedroomsLabel: "Bedrooms",
  bathroomsLabel: "Bathrooms",
  interiorLabel: "Interior area",
  outdoorLabel: "Outdoor area",
  blockLabel: "Block",
  floorLabel: "Floor",
  orientationLabel: "Orientation",
  statusLabel: "Status",
  completionLabel: "Completion",
  infoTabLabel: "Info",
  benefitsTabLabel: "Included",
  featuresLabel: "What comes with the home",
  ctaLabel: "Book a call",
  viewPlanLabel: "View the floor plan",
  mediaLabel: "Photographs and plans",
  infoLabel: "Residence details",
  lightboxLabel: "Residence media, full screen",
  expandLabel: "Expand",
  closeLabel: "Close",
  previousLabel: "Previous image",
  nextLabel: "Next image",
  dragHint: "Swipe for more",
  similarEyebrow: "Other residences",
  similarHeadingLines: ["Others that may", "suit you as well"],
  backLabel: "All residences",
  backHref: "/residences",
};
